// Action type constants for upcoming transactions
export const FETCH_UPCOMING_TRANSACTIONS_REQUEST = 'FETCH_UPCOMING_TRANSACTIONS_REQUEST';
export const FETCH_UPCOMING_TRANSACTIONS_SUCCESS = 'FETCH_UPCOMING_TRANSACTIONS_SUCCESS';
export const FETCH_UPCOMING_TRANSACTIONS_FAILURE = 'FETCH_UPCOMING_TRANSACTIONS_FAILURE';
